name: webview_useragent_platform_interface
description: A common platform interface for the webview_useragent plugin.
repository: https://github.com/strysk/webview_useragent/tree/main/webview_useragent_platform_interface
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
