name: webview_useragent_platform_interface
description: A common platform interface for the webview_useragent plugin.
repository: https://github.com/strysk/webview_useragent/tree/main/webview_useragent_platform_interface
version: 1.0.0

environment:
  sdk: '^3.1.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
