name: webview_useragent_ios
description: The iOS implementation of webview_useragent.
repository: https://github.com/strysk/webview_useragent/tree/main/webview_useragent_ios
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  webview_useragent_platform_interface:
    path: ../webview_useragent_platform_interface

flutter:
  plugin:
    implements: webview_useragent
    platforms:
      ios:
        pluginClass: WebviewUserAgentPlugin
        dartPluginClass: WebviewUserAgentIOS
